name: CMake build and test workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cmake:
    runs-on:
      - ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: threeal/cmake-action@v2.1.0
        with:
          cmake-version: latest
        
      - name: Pre-build configuration
        run: |-
          apt-get update
          apt-get install -y clang ninja-build lld
      
      - name: CMake configuration phase
        run: |-
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=/usr/bin/clang \
                -DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
                -DCMAKE_LINKER_TYPE=LLD \
                -GNinja \
                -S . \
                -B ./build

      - name: CMake build phase
        run: cmake --build ./build

      - name: CMake test phase
        run: ctest --test-dir ./build/release/test
