name: CMake build and test workflow
run-name: ${{ github.actor }} has done ${{ github.event_name }} to master branch
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  cmake:
    runs-on: ${{ inputs.os }}
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event"
      - run: echo "This job is running on ${{ runner.os }}"

      - uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to runner"

      - name: CMake configuration and build phase
        uses: threeal/cmake-action@v2.1.0
        with:
          source-dir: .
          build-dir: build
          options: CMAKE_BUILD_TYPE=Release

      - name: CMake test phase
        run: ctest --test-dir ./build/test
      - run: echo "Job status is ${{ job.status }}"
