name: ubuntu-latest
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ubuntu-latest-build:
    uses: ./.github/workflows/main.yaml
    with:
      os: ubuntu-latest
