name: windows-latest
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  windows-latest-build:
    uses: ./.github/workflows/main.yaml
    with:
      os: windows-latest
